spring:
  profiles:
    active: native
  #    active: native,git
  rabbitmq:
    host: ${myRabbitMQ.name:localhost}
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/VlasovArtem/SpringBootConfiguration
#          clone-on-start: true
#          password:
#          username:
        native:
#          search-locations: file://${user.home}/git/spring-boot-microservices/native-file-properties-example/
          search-locations: file:./native-file-properties-example/,file:./native-file-properties-example/{application}
  application:
    name: PhotoAppAPIConfigServer
server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,env,configprops