server:
  port: 8011

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: zuul

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace