server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  zipkin:
    base-url: 'http://localhost:9411'
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  level:
    org.avlasov.photoapp.api.users.data.AlbumsServiceClient: DEBUG

feign:
  hystrix:
    enabled: true
