gateway: 
  ip: ${myGateway.name:localhost}

token: 
  expiration_time: 86400000
  secret: '{cipher}AQAKfHe0NNXv9E7WAQsQZB46sxeXk8hzoNPNd0W8CJ38DsaPP9OeON/aSpjwwzBoqPbZRDv1UntCTlBovqbfnDynR4vvE+aFy7GSCpSF9TTWFcVlly5DZ8evMkAZ0JUDq6eGufFJcfoSWthHCFv1T8gM3uR5zQVdGMmn5dfNqe0zSOPm/2xDAt9VODhbYjVU8ULbbOn2R3psK5XLG95S4M+idLR1lKm2zrGCgE2V0YQ5MiEAhn25lRUcngTKyNWA15+aCX5wC08cAGFNtey5ZXP4G779+VUxXJlmv49mwwkIRFxlLIIO1UCUye7w0Qj7fNp0B8HMoC5NG5Wr48hR664LP9Go0ETSdn2/2RILL361iXmG8fGmcdkZFtlNrFmAYjU='

api:
  url:
    albums: http://albums-ws/api/users/%s/albums
  exception:
    albums-not-found: 'Users albums are not found'

eureka:
  client:
    service-url:
      defaultZone: http://${myEureka.name}:${myEureka.password}@${myEureka.host-name:localhost}:8010/eureka

myEureka:
  password: '{cipher}AQApEixf4/q++KxfhVdHg33LoIK9PW0AGDHh8BaCI/rUIc+Ae0ZrP9VMsb4sxuYesOUI1tn9iHzTk1mXPFGC6EFUyeozX09pZXEwEItWQvFXTyeNvAn6H6ciQukJiU3ayzGX+fm9N5RFbGELOVnetbBFygLTsxN4KjcvyGr6AtB5dtZ3LcwIBPWMNXhTkaPCqh59lhPTfqkLhUL8P7e/p4UrQqXyHUOx+qt3kXwMymSKgTBgn3Bbqf/T8vTi0LRWxysTqC/tsFNYkydYsLNd/MtRBN9Y8LiXPPq/XoDOIlC9BzkiUDOwoErnqb2EU7GongukYPs/gxy+EK0pmRGAKeSvO3PELsY67AQcK18E+qv0fcpv0hOe+NuZ+L9ZY1igaGc='
  name: '{cipher}AQApEixf4/q++KxfhVdHg33LoIK9PW0AGDHh8BaCI/rUIc+Ae0ZrP9VMsb4sxuYesOUI1tn9iHzTk1mXPFGC6EFUyeozX09pZXEwEItWQvFXTyeNvAn6H6ciQukJiU3ayzGX+fm9N5RFbGELOVnetbBFygLTsxN4KjcvyGr6AtB5dtZ3LcwIBPWMNXhTkaPCqh59lhPTfqkLhUL8P7e/p4UrQqXyHUOx+qt3kXwMymSKgTBgn3Bbqf/T8vTi0LRWxysTqC/tsFNYkydYsLNd/MtRBN9Y8LiXPPq/XoDOIlC9BzkiUDOwoErnqb2EU7GongukYPs/gxy+EK0pmRGAKeSvO3PELsY67AQcK18E+qv0fcpv0hOe+NuZ+L9ZY1igaGc='

spring:
  rabbitmq:
    host: ${myRabbitMQ.name:localhost}
    port: 5672
    username: guest
    password: guest