server:
  port: 8010

spring:
  application.name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    peer-node-read-timeout-ms: 30000

logging:
  file: discovery-ws.log